# Generated by Django 4.2.13 on 2024-08-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_service_image_service_duration_service_price_and_more'),
        ('booking', '0003_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.ForeignKey(default='New service', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='pages.service', unique=True),
        ),
    ]
