# Generated by Django 4.2.13 on 2024-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_time_slot_alter_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.TimeField(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
