# Generated by Django 4.2.13 on 2024-08-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_service_image_service_duration_service_price_and_more'),
        ('booking', '0004_alter_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reserved', to='pages.service'),
        ),
    ]
