# Generated by Django 4.2.13 on 2024-08-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
