# Generated by Django 4.2.13 on 2024-08-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_delete_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('requested_date', 'requested_time')},
        ),
    ]
